New dev branch

diff --git a/.github/workflows/build_ci.yml b/.github/workflows/build_ci.yml
--- a/.github/workflows/build_ci.yml
+++ b/.github/workflows/build_ci.yml
@@ -4,7 +4,8 @@ on:
 
   push:
     branches:
-      - main
+      - dev/ci/anim_th_builds
+      # - main
 
 env:
   JENKINS_SERVER_TOKEN: ${{ secrets.JENKINS_SERVER_TOKEN }}
@@ -13,25 +14,133 @@ env:
 
 jobs:
 
-  build_linux:      
+  # build_userlib_sdk_linux:      
+  #   if: ${{ github.repository_owner == 'OpenRadioss' }}
+  #   runs-on: ["linux64","prod"]
+  #   container: 
+  #     image: fr-qafactorydev.europe.altair.com/trigger-jenkins
+  #     credentials: 
+  #       username: ${{secrets.DOCKER_REGISTRY_USER}}
+  #       password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
+  #     volumes: 
+  #       - /etc/localtime:/etc/localtime:ro  
+  #       - /etc/docker/certs.d:/etc/docker/certs.d:ro
+
+  #   env:
+  #     USERLIB_SDK_JOB_NAME: "github_build_userlib_sdk_linux64"
+  
+  #   steps:
+  #     - name: Trigger jenkins
+  #       run: |
+  #         # We use ceritificate to connect to jenkins and a crumb (new wayt to do)
+  #         crumb=$(curl -u adminqa:${JENKINS_SERVER_TOKEN} --capath "/etc/docker/certs.d/${CERTS_SERVER_NAME}" --cacert "/etc/docker/certs.d/${CERTS_SERVER_NAME}/wildcard_europe_altair_com.crt" -s "${JENKINS_SERVER_URL}/crumbIssuer/api/json" | grep -oP '"crumb":"\K[^"]+')
+  #         curl -u adminqa:${JENKINS_SERVER_TOKEN} --capath "/etc/docker/certs.d/${CERTS_SERVER_NAME}" --cacert "/etc/docker/certs.d/${CERTS_SERVER_NAME}/wildcard_europe_altair_com.crt" -H "Jenkins-Crumb:$crumb" -X POST "${JENKINS_SERVER_URL}/job/${USERLIB_SDK_JOB_NAME}/buildWithParameters?commit_id=${GITHUB_SHA}"
+
+  build_tools_linux:
     if: ${{ github.repository_owner == 'OpenRadioss' }}
-    runs-on: ["linux64","prod"]
+    # DEV ONLY # runs-on: ["linux64","dev"] 
+    # runs-on: ["linux64","prod"]
+    runs-on: ["linux64","dev"] 
     container: 
-      image: fr-qafactorydev.europe.altair.com/trigger-jenkins
+      image: fr-qafactorydev.europe.altair.com/build-linux64_gf:cos8-ompi411-devts11
       credentials: 
         username: ${{secrets.DOCKER_REGISTRY_USER}}
         password: ${{secrets.DOCKER_REGISTRY_PASSWD}}
       volumes: 
-        - /etc/localtime:/etc/localtime:ro  
-        - /etc/docker/certs.d:/etc/docker/certs.d:ro
-
-    env:
-      USERLIB_SDK_JOB_NAME: "github_build_userlib_sdk_linux64"
+        - /etc/localtime:/etc/localtime:ro
   
-    steps:
-      - name: Trigger jenkins
-        run: |
-          # We use ceritificate to connect to jenkins and a crumb (new wayt to do)
-          crumb=$(curl -u adminqa:${JENKINS_SERVER_TOKEN} --capath "/etc/docker/certs.d/${CERTS_SERVER_NAME}" --cacert "/etc/docker/certs.d/${CERTS_SERVER_NAME}/wildcard_europe_altair_com.crt" -s "${JENKINS_SERVER_URL}/crumbIssuer/api/json" | grep -oP '"crumb":"\K[^"]+')
-          curl -u adminqa:${JENKINS_SERVER_TOKEN} --capath "/etc/docker/certs.d/${CERTS_SERVER_NAME}" --cacert "/etc/docker/certs.d/${CERTS_SERVER_NAME}/wildcard_europe_altair_com.crt" -H "Jenkins-Crumb:$crumb" -X POST "${JENKINS_SERVER_URL}/job/${USERLIB_SDK_JOB_NAME}/buildWithParameters?commit_id=${GITHUB_SHA}"
+    env:
+      STATUS_BUILD: 0
+      os: linux64
+      ANIM_TO_VTK_DIR: output_converters/anim_to_vtk
+      TH_TO_CSV: output_converters/th_to_csv
 
+    steps:
+
+      # # Set the working dir suffixed with branch name
+      # - name: Set workdir 
+      #   run: |
+      #     echo "WORKDIR=latest" >> $GITHUB_ENV
+
+      # - name: Create branch oriented WS directory & integration WS
+      #   run: |
+      #     mkdir -p ${{ env.WORKDIR }}
+
+      - name: Clean local exe dir
+        # working-directory: ${{ env.WORKDIR }}
+        run: |
+          rm -rf exec
+          md5sum exec/* || echo "Nothing in exec/" 
+
+      # # Get last git modifications, don't clean before (way to keep persistent obj files)
+      # - name: Checkout git sources
+      #   uses: actions/checkout@v4
+      #   with:
+      #     path: ${{ env.WORKDIR }}
+      #     clean: 'false'
+      #     lfs: 'true'
+      #     ref: ${{ env.LAST_STABLE_TAG_NAME }}
+
+      - name: Running builds
+        # working-directory: ${{ env.WORKDIR }}
+        run: |
+          mkdir exec
+          source /home/adminqa/.bashrc
+
+          cmd="./build.bash"
+          echo "========================================="
+          echo "--  BUILD tools for anim_to_vtk (${{ env.os }}) --"   
+          echo "--  $cmd --"   
+          echo "========================================="
+
+          cd ${{ env.ANIM_TO_VTK_DIR }}/${{ env.os }}
+          pwd
+          eval $cmd
+
+          cmd="./build.bash"
+          echo "========================================="
+          echo "--  BUILD tools for th_to_csv (${{ env.os }}) --"   
+          echo "--  $cmd --"   
+          echo "========================================="
+
+          cd -
+          pwd
+          ${{ env.TH_TO_CSV }}/${{ env.os }}
+          eval $cmd
+
+          # Set correct end of step status (if not an email will be sent)
+          echo "STATUS_BUILD=1" >> $GITHUB_ENV
+
+      - name: Managing step execution
+        if: ${{ always() }}
+        run: |
+
+          MAILMSG="Some error(s) has(ve) been raised during workflow execution:\n\n"
+          echo -e "\n#### STATUS_STEP_BUILD ${{ env.os }} ###"
+          if [ "$STATUS_BUILD" = 0 ]
+          then
+            echo -e "Status\t[ \033[31;2;1mFAILED\033[0m ]" 
+            MAILMSG="The build tools ${{ env.os }} has failed \n"
+
+            # Send email 
+
+            # Setting SMTP server (docker host)
+            DOCKER_HOST=`/sbin/ip route|awk '/default/ { print $3 }'`
+            echo "set smtp=smtp://${DOCKER_HOST}:25" >> /etc/mail.rc 
+
+            # Print message in log 
+            echo -e $MAILMSG
+
+            # Send email
+            echo -e "$MAILMSG" | Mail -r $FROM_EMAIL -s "Error in Github CI repo ${{ github.repository }} (${{ github.sha }})" $TO_EMAIL
+
+          else
+            echo -e "Status\t[ \033[32;2;1mOK\033[0m ]"
+          fi
+
+      # # Upload artifact
+      # - name: Upload built artifacts
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: tools-${{ env.os }}
+      #     path: exec
